version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      .env
  backend:
    depends_on:
      db:
        condition: service_started
    environment:
      - REDIS_URL=redis:db:6379/0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
volumes:
  db:
    driver: local